name: Build flash-attention Wheels for ROCm

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of flash-attention to build: (format: v2.3.4/v2.3.4.post1)'
        default: 'v2.3.4'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag of flash-attention to build (format: v2.3.4/v2.3.4.post1)'
        default: 'v2.3.4'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build_wheels:
    name: Build wheels for Python ${{ matrix.pyver }}, ROCm ${{ matrix.rocm }}, and Torch ${{ matrix.torchver }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        pyver: ["3.10"]
        rocm: ["6.0"]
        torchver: ["2.3.1"]
    defaults:
      run:
        shell: bash
    env:
        ROCMVER: ${{ matrix.rocm }}
        PCKGVER: ${{ inputs.version }}

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        if: runner.os == 'Linux'
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true

      - uses: actions/checkout@v4
        #with:
        #  submodules: 'recursive'

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyver }}

      - name: Install Dependencies
        run: |
          # --- Install ROCm SDK

          export ROCM_VERSION=${{ matrix.rocm }}
          export TORCH_VERSION=${{ matrix.torchver }}

          [ ! -d /etc/apt/keyrings ] && sudo mkdir --parents --mode=0755 /etc/apt/keyrings
          wget https://repo.radeon.com/rocm/rocm.gpg.key -O - | gpg --dearmor | sudo tee /etc/apt/keyrings/rocm.gpg > /dev/null
          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/$ROCM_VERSION focal main" | sudo tee --append /etc/apt/sources.list.d/rocm.list
          echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/rocm-pin-600
          
          sudo apt update
          sudo apt install rocm-hip-sdk -y
          sudo apt clean -y

          echo "/opt/rocm/bin" >> $GITHUB_PATH
          echo "ROCM_PATH=/opt/rocm" >> $GITHUB_ENV
          echo "ROCM_VERSION=$ROCM_VERSION" >> $GITHUB_ENV
          echo "USE_ROCM=1" >> $GITHUB_ENV

          # --- Install dependencies

          python3 -m ensurepip --upgrade
          pip3 install torch==${{ matrix.torchver }} --index-url="https://download.pytorch.org/whl/rocm$ROCM_VERSION"
          pip3 install --upgrade build setuptools wheel packaging ninja psutil
          pip3 cache purge

      - name: Build Wheel
        id: build-wheel
        run: |
          rocm_version="${{ matrix.rocm }}"
          package_version="${PCKGVER#v}"

          export MAX_JOBS=1
          export FLASH_ATTENTION_FORCE_BUILD=TRUE
          export FLASH_ATTENTION_FORCE_CXX11_ABI=FALSE
          export BUILD_TARGET=rocm
          export GPU_ARCHS="gfx942"

          python3 setup.py bdist_wheel --dist-dir=dist

          wheel=$(ls ./dist/*.whl)
          wheel_name=$(basename "$wheel")
          new_wheel_name="${wheel_name//flash_attn-$package_version-/flash_attn-$package_version+rocm$rocm_version+torch${{ matrix.torchver }}cxx11abiFALSE-}"
          mv "$wheel" "./dist/$new_wheel_name"

      - uses: actions/upload-artifact@v3
        with:
          name: 'rocm-wheels'
          path: ./dist/*.whl
          
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.6.1
        continue-on-error: true
        with:
          file: ./dist/*.whl
          tag: ${{ inputs.version }}
          file_glob: true
          overwrite: true
          release_name: ${{ inputs.version }}
